# version: "3"
services:

  # nacos
  nacos:
    image: nacos/nacos-server:latest
    hostname: nacos-server
    restart: always
    container_name: integrated-example-nacos
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
      # - NACOS_AUTH_ENABLE=true
      # - NACOS_AUTH_TOKEN=dGhpcyBpcyBhIHNlY3JldCBrZXkgdGhhdCBpcyBzYWZlIHRvIGJlIHVzZWQgd2l0aCBKU1Q=
      # - NACOS_AUTH_IDENTITY_KEY=custom_server_identity_key
      # - NACOS_AUTH_IDENTITY_VALUE=custom_server_identity_value
    ports:
      - "8848:8848"
      - "9848:9848"
    volumes:
      - ../config-init/nacos/data/:/home/nacos/data # 挂载数据目录以持久化数据
    networks:
      - integrated-network

  # mysql
  mysql:
    image: mysql:8.0
    container_name: integrated-example-mysql
    hostname: integrated-mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=integrated_storage
    ports:
      - "3306:3306"
    volumes:
      - ../config-init/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ../config-init/mysql8/my.cnf:/etc/mysql/my.cnf
      - ../config-init/mysql8/data:/var/lib/mysql
    networks:
      - integrated-network

  # rocketMQ
  rmqnamesrv:
    image: apache/rocketmq:4.9.4
    hostname: rocketmq
    restart: always
    container_name: integrated-example-rmqnamesrv
    ports:
      - "9876:9876"
    command: sh mqnamesrv
    networks:
      - integrated-network
    # healthcheck:
      # test: ["CMD-SHELL", "nc -z localhost 9876 || exit 1"]
      # interval: 10s
      # timeout: 5s
      # retries: 3  
    
  rmqbroker:
    image: apache/rocketmq:4.9.4
    hostname: rmqbroker  # 添加hostname
    restart: always
    container_name: integrated-example-rmqbroker
    ports:
      - "10909:10909"
      - "10911:10911"
    volumes:
      - ../config-init/rocketmq/broker.conf:/opt/rocketmq-4.9.4/conf/broker.conf
    environment:
      NAMESRV_ADDR: "rmqnamesrv:9876"
      JAVA_OPTS: " -Duser.home=/opt"
      JAVA_OPT_EXT: "-server -Xms256m -Xmx256m -Xmn128m"
    command: sh mqbroker -c /opt/rocketmq-4.9.4/conf/broker.conf
    depends_on:
      - rmqnamesrv
    networks:
      - integrated-network
    # healthcheck:
      # test: ["CMD-SHELL", "nc -z localhost 10911 || exit 1"]
      # interval: 10s
      # timeout: 5s
      # retries: 3
      
  rmqdashboard:
    image: apacherocketmq/rocketmq-dashboard:latest
    hostname: rmqdashboard
    restart: always
    container_name: integrated-example-rmqdashboard
    environment:
      - JAVA_OPTS=-Drocketmq.namesrv.addr=rmqnamesrv:9876
    ports:
      - "9090:8080"
    # mem_limit: 1g  # 限制容器最大内存为 512 MB
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    depends_on:
      - rmqnamesrv
      - rmqbroker
    networks:
      - integrated-network
    # healthcheck:
      # test: ["CMD-SHELL", "nc -z localhost 8080 || exit 1"]
      # interval: 10s
      # timeout: 5s
      # retries: 3
      
  # seata
  seata-server:
    image: seataio/seata-server:latest   # seataio/seata-server:1.5.1
    hostname: seata-server
    restart: always
    container_name: integrated-example-seata-server
    ports:
      - "8091:8091"
    environment:
      - SEATA_PORT=8091
      - STORE_MODE=file
    networks:
      - integrated-network

networks:
  integrated-network:
    driver: bridge
