# version: "3"
services:

  # nacos
  nacos:
    image: nacos/nacos-server:v2.4.2
    hostname: nacos-server
    restart: always
    container_name: integrated-example-nacos
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
      - NACOS_AUTH_ENABLE=true
      - NACOS_AUTH_TOKEN=dGhpcyBpcyBhIHNlY3JldCBrZXkgdGhhdCBpcyBzYWZlIHRvIGJlIHVzZWQgd2l0aCBKU1Q=
      - NACOS_AUTH_IDENTITY_KEY=custom_server_identity_key
      - NACOS_AUTH_IDENTITY_VALUE=custom_server_identity_value
    ports:
      - "8848:8848"

  # mysql
  mysql:
    image: mysql:8.0
    container_name: integrated-example-mysql
    hostname: integrated-mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=integrated_storage
    ports:
      - "3306:3306"
    volumes:
      - ../config-init/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ../config-init/mysql8/my.cnf:/etc/mysql/my.cnf
      - ../config-init/mysql8/data:/var/lib/mysql

  # rocketMQ
  rmqnamesrv:
    image: apache/rocketmq:4.9.4
    hostname: rocketmq
    restart: always
    container_name: integrated-example-rmqnamesrv
    ports:
      - "9876:9876"
    command: sh mqnamesrv
    
  rmqbroker:
    image: apache/rocketmq:4.9.4
    restart: always
    container_name: integrated-example-rmqbroker
    ports:
      - "10909:10909"
      - "10911:10911"
    volumes:
      - ../config-init/rocketmq/broker.conf:/opt/rocketmq-4.9.4/conf/broker.conf
    environment:
      NAMESRV_ADDR: "rmqnamesrv:9876"
      JAVA_OPTS: " -Duser.home=/opt"
      JAVA_OPT_EXT: "-server -Xms128m -Xmx128m -Xmn128m"
    command: sh mqbroker -c /opt/rocketmq-4.9.4/conf/broker.conf
    depends_on:
      - rmqnamesrv
    extra_hosts:
      - "host.docker.internal:host-gateway"  # 使容器能够通过宿主机 IP 访问
    networks:
      - rocketmq-net
 
  # rmqdashboard:
    # image: openjdk:17  # 或者自定义镜像
    # container_name: integrated-example-rmqdashboard
    # restart: always
    # ports:
      # - "8080:8080"
    # volumes:
      # - /usr/lib/jvm/java-17-openjdk:/usr/lib/jvm/java-17-openjdk  # 挂载本地 JDK
      # - /app/software/rocketmq-dashboard:/app  # 挂载应用程序目录
    # environment:
      # JAVA_HOME: /usr/lib/jvm/java-17-openjdk  # 设置 JAVA_HOME 环境变量
      # PATH: $JAVA_HOME/bin:$PATH  # 更新 PATH 环境变量
      # NAMESRV_ADDR: "rmqnamesrv:9876"
    # command: java -jar /app/rocketmq-dashboard-2.0.0.jar  # 运行 JAR 文件
    # logging:
      # driver: "json-file"
      # options:
        # max-size: "10m"
        # max-file: "3"
    # mem_limit: 512m  # 限制容器最大内存为 512 MB
    # mem_reservation: 256m  # 容器预留内存为 256 MB
    # networks:
      # - rocketmq-net
 
  # seata
  seata-server:
    image: seataio/seata-server:1.5.1
    hostname: seata-server
    restart: always
    container_name: integrated-example-seata-server
    ports:
      - "8091:8091"
    environment:
      - SEATA_PORT=8091
      - STORE_MODE=file

networks:
  rocketmq-net:
    driver: bridge      